# Generated by Django 6.0.5 on 2026-05-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('home', 'Homepage'), ('about', 'About Us'), ('products', 'Products'), ('certifications', 'Certifications'), ('blog', 'Blog'), ('branding', 'Branding / Private Label'), ('contact', 'Contact'), ('export', 'Export'), ('packaging', 'Packaging')], help_text='Which page this hero background is for.', max_length=50, unique=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload a hero background image (JPEG, PNG, WebP).', null=True, upload_to='backgrounds/')),
                ('video', models.FileField(blank=True, help_text='Upload a hero background video (MP4, WebM). Used only when media type is Video.', null=True, upload_to='backgrounds/videos/')),
            ],
            options={
                'verbose_name': 'Hero Background',
                'verbose_name_plural': 'Hero Backgrounds',
                'ordering': ['page'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX', max_length=50),
        ),
    ]
