# Generated by Django 6.0.5 on 2026-06-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_heromedia_alter_sitesettings_google_analytics_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a product image (JPEG, PNG, WebP).', null=True, upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_en',
            field=models.CharField(default='Vinaigre du Maroc', max_length=100),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='author_fr',
            field=models.CharField(default='Vinaigre du Maroc', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Vinaigre du Maroc', max_length=200),
        ),
    ]
