# Generated by Django 6.0.5 on 2026-06-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_image_alter_blogpost_author_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload category thumbnail picture', null=True, upload_to='categories/'),
        ),
    ]
